spring:
  application:
    name: demo
  datasource:
    url: jdbc:sqlite:mi_base_de_datos.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
